baseurl = "https://staging-dot-loyall-www.appspot.com"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

GoogleAnalytics = "UA-82408067-1"
Copyright = "Copyright &copy; 2016, Loyall GmbH; all rights reserved."

[Author]
    name = "Pascal Aubort"

#################### Languages ####################
IsMultiLingual = true
DefaultContentLanguage = "de"
DefaultContentLanguageInSubdir = false

[Languages]
[Languages.de]
    weight = 0
    title = "Loyall - IT Beratung und Google Apps Dienstleistungen"
    languageName = "Deutsch"

[[Languages.de.menu.main]]
    name = "Startseite"
    weight = -110
    identifier = "home"
    url = "/"
[[Languages.de.menu.main]]
    name = "Dienstleistungen"
    weight = -100
    identifier = "services"
    url = "/services/"
[[Languages.de.menu.main]]
    name = "Für Schulen"
    weight = -90
    identifier = "googleforeducation"
    url = "/for-education/"
[[Languages.de.menu.main]]
    name = "Für Unternehmen"
    weight = -80
    identifier = "forbusiness"
    url = "/for-business/"
[[Languages.de.menu.main]]
    name = "Über uns"
    weight = -70
    identifier = "aboutus"
    url = "/about-us/"

[Languages.en]
    weight = 10
    title = "Loyall - IT Consulting and Google Apps Services"
    languageName = "English"
    
[[Languages.en.menu.main]]
    name = "Home"
    weight = -110
    identifier = "home"
    url = "/"
[[Languages.en.menu.main]]
    name = "Services"
    weight = -100
    identifier = "services"
    url = "/services/"
[[Languages.en.menu.main]]
    name = "For Education"
    weight = -90
    identifier = "foreducation"
    url = "/for-education/"
[[Languages.en.menu.main]]
    name = "For Business"
    weight = -80
    identifier = "forbusiness"
    url = "/for-business/"
[[Languages.en.menu.main]]
    name = "About us"
    weight = -70
    identifier = "aboutus"
    url = "/about-us/"
 


[params]
    primaryPhone = "+41 44 585 33 00"
    
    description = ""
    #recaptchaSitekey = "6LeURygTAAAAAAfeKQjIzStD2zAPA3gRrxmA0oMK"
    
    [params.layout]
    headerColor = "mdl-color--white"
    navigationLinkColor = "mdl-color-text--primary"
    navigationLinkColor_hover = "mdl-color-text--primary-light"
    
    [[params.sections]]
    sectionId = "1"
    prettyName = "Home"
    path = ""
    
    [[params.sections]]
    sectionId = "2"
    prettyName = "Services"
    path = "services"
    
    [[params.sections]]
    sectionId = "3"
    prettyName = "Google for Education"
    subtitle = "Google for Education"
    path = "google-for-education"
    
    [[params.sections]]
    sectionId = "4"
    prettyName = "Google for Work"
    subtitle = "Google for Work"
    path = "google-for-work"
    
    [[params.sections]]
    sectionId = "5"
    prettyName = "About us"
    subtitle = "Google for Work"
    path = "about-us"
    
    
    # [[params.sections]]
    # sectionId = "3"
    # prettyName = "Partners & Clients"
    # background = "color-primary-dark"
    # partial = "home.html"
    
    # [[params.sections]]
    # sectionId = "4"
    # prettyName = "Contact us"
    # background = "color-primary-dark"
    # partial = "home.html"