#baseurl = "//skallab.co"
languageCode = "en-us"
title = "skallab"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
    description = ""
    author = "Pascal Aubort"
    googleAnalytics = ""