baseurl = "loyall.ch"
languageCode = "en-us"
# title = "Loyall GmbH - IT Consulting and Google Apps Specialists"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"


[Author]
    name = "Pascal Aubort"
DefaultContentLanguage = "en"
GoogleAnalytics = "UA-82408067-1"


[params]
    description = ""
    #recaptchaSitekey = "6LeURygTAAAAAAfeKQjIzStD2zAPA3gRrxmA0oMK"
    
    languages = ["Français", "Deutsch", "English"]
    
    [params.layout]
    headerColor = "mdl-color--white"
    navigationLinkColor = "mdl-color-text--primary"
    navigationLinkColor_hover = "mdl-color-text--primary-light"
    
    [[params.sections]]
    sectionId = "1"
    prettyName = "Home"
    title = "Trusted Advisory for your IT"
    subtitle = "Loyall Gmbh is your trusted partner for IT projects and Google Apps for Work and Education"
    url = "/"
    
    [[params.sections]]
    sectionId = "2"
    prettyName = "Google for Work"
    subtitle = "Google for Work"
    url = "/google-for-work"
    
    [[params.sections]]
    sectionId = "3"
    prettyName = "Google for Education"
    subtitle = "Google for Education"
    url = "/google-for-education"
    
    # [[params.sections]]
    # sectionId = "3"
    # prettyName = "Partners & Clients"
    # background = "color-primary-dark"
    # partial = "home.html"
    
    # [[params.sections]]
    # sectionId = "4"
    # prettyName = "Contact us"
    # background = "color-primary-dark"
    # partial = "home.html"