baseurl = ""
#languageCode = "en-us"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
# googleAnalytics = "UA-82408067-1"

GoogleAnalytics = "UA-82408067-1"
Copyright = "Copyright &copy; 2016, Loyall GmbH; all rights reserved."


[Author]
    name = "Pascal Aubort"

#################### Languages ####################
IsMultiLingual = true
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true

[Languages]
[Languages.en]
    weight = 1
    title = "Loyall - IT Consulting and Google Apps Services"
    languageName = "English"
    
[[Languages.en.menu.main]]
    name = "Home"
    weight = -110
    identifier = "home"
    url = "/"
[[Languages.en.menu.main]]
    name = "Services"
    weight = -100
    identifier = "services"
    url = "/services/"
[[Languages.en.menu.main]]
    name = "Google for Education"
    weight = -90
    identifier = "googleforeducation"
    url = "/google-for-education/"
[[Languages.en.menu.main]]
    name = "Google for Work"
    weight = -80
    identifier = "googleforwork"
    url = "/google-for-work/"
[[Languages.en.menu.main]]
    name = "About us"
    weight = -70
    identifier = "aboutus"
    url = "/about-us/"
  
    
[Languages.de]
    weight = 2
    title = "Loyall - IT Beratung und Google Apps Dienstleistungen"
    languageName = "Deutsch"

[[Languages.de.menu.main]]
    name = "Startseite"
    weight = -110
    identifier = "home"
    url = "/"
[[Languages.de.menu.main]]
    name = "Dienstleistungen"
    weight = -100
    identifier = "services"
    url = "/services/"
[[Languages.de.menu.main]]
    name = "Google for Education"
    weight = -90
    identifier = "googleforeducation"
    url = "/google-for-education/"
[[Languages.de.menu.main]]
    name = "Google for Work"
    weight = -80
    identifier = "googleforwork"
    url = "/google-for-work/"
[[Languages.de.menu.main]]
    name = "About us"
    weight = -70
    identifier = "aboutus"
    url = "/about-us/"


[params]
    description = ""
    #recaptchaSitekey = "6LeURygTAAAAAAfeKQjIzStD2zAPA3gRrxmA0oMK"
    
    [params.layout]
    headerColor = "mdl-color--white"
    navigationLinkColor = "mdl-color-text--primary"
    navigationLinkColor_hover = "mdl-color-text--primary-light"
    
    [[params.sections]]
    sectionId = "1"
    prettyName = "Home"
    path = ""
    
    [[params.sections]]
    sectionId = "2"
    prettyName = "Services"
    path = "services"
    
    [[params.sections]]
    sectionId = "3"
    prettyName = "Google for Education"
    subtitle = "Google for Education"
    path = "google-for-education"
    
    [[params.sections]]
    sectionId = "4"
    prettyName = "Google for Work"
    subtitle = "Google for Work"
    path = "google-for-work"
    
    [[params.sections]]
    sectionId = "5"
    prettyName = "About us"
    subtitle = "Google for Work"
    path = "about-us"
    
    
    # [[params.sections]]
    # sectionId = "3"
    # prettyName = "Partners & Clients"
    # background = "color-primary-dark"
    # partial = "home.html"
    
    # [[params.sections]]
    # sectionId = "4"
    # prettyName = "Contact us"
    # background = "color-primary-dark"
    # partial = "home.html"