baseurl = "loyall.ch"
languageCode = "en-us"
title = "Loyall GmbH - IT Consulting and Google Apps Specialists"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
    description = ""
    author = "Pascal Aubort"
    googleAnalytics = "UA-82408067-1"
    #recaptchaSitekey = "6LeURygTAAAAAAfeKQjIzStD2zAPA3gRrxmA0oMK"
    
    languages = ["Français", "Deutsch", "English"]
    
    [params.layout]
    headerColor = "mdl-color--white"
    navigationLinkColor = "mdl-color-text--primary"
    navigationLinkColor_hover = "mdl-color-text--primary-light"
    
    [[params.sections]]
    sectionId = "1"
    prettyName = "About us"
    subtitle = "Trusted Advisor for your IT"
    # background = "color-primary-dark"
    partial = "home.html"
    
    [[params.sections]]
    sectionId = "2"
    prettyName = "Google for Work"
    subtitle = "Google for Work"
    # background = "color-primary-dark"
    partial = "google-for-work.html"
    
    [[params.sections]]
    sectionId = "3"
    prettyName = "Google for Education"
    subtitle = "Google for Education"
    # background = "color-primary-dark"
    partial = "google-for-education.html"
    
    # [[params.sections]]
    # sectionId = "3"
    # prettyName = "Partners & Clients"
    # background = "color-primary-dark"
    # partial = "home.html"
    
    # [[params.sections]]
    # sectionId = "4"
    # prettyName = "Contact us"
    # background = "color-primary-dark"
    # partial = "home.html"