baseurl = "https://staging-dot-loyall-www.appspot.com"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[Author]
    name = "Pascal Aubort"

#################### Languages ####################
IsMultiLingual = true
DefaultContentLanguage = "de"
DefaultContentLanguageInSubdir = false

[Languages]
[Languages.de]
    weight = 1
    title = "Deutsch Titel"
    languageName = "Deutsch"

[[Languages.de.menu.main]]
    name = "Startseite"
    weight = -100
    identifier = "home"
    url = "/"

[[Languages.de.menu.main]]
    name = "Kredit"
    weight = -110
    identifier = "contact"
    url = "/credits/"


[Languages.en]
    weight = 2
    title = "English title"
    languageName = "English"
    
[[Languages.en.menu.main]]
    name = "Home"
    weight = -100
    identifier = "home"
    url = "/"

[[Languages.en.menu.main]]
    name = "Credits"
    weight = -110
    identifier = "contact"
    url = "/credits/"