baseurl = ""
#languageCode = "en-us"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
# googleAnalytics = "UA-82408067-1"

GoogleAnalytics = "UA-82408067-1"
Copyright = "Copyright &copy; 2016, Loyall GmbH; all rights reserved."


[Author]
    name = "Pascal Aubort"

#################### Languages ####################
IsMultiLingual = true
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true

[Languages]
    [Languages.en]
        weight = 1
        title = "Loyall - IT Consulting and Google Apps Services"
        languageName = "English"
    
    [Languages.de]
        weight = 2
        title = "Loyall - IT Beratung und Google Apps Dienstleistungen"
        languageName = "Deutsch"

[params]
    description = ""
    #recaptchaSitekey = "6LeURygTAAAAAAfeKQjIzStD2zAPA3gRrxmA0oMK"
    
    [params.layout]
    headerColor = "mdl-color--white"
    navigationLinkColor = "mdl-color-text--primary"
    navigationLinkColor_hover = "mdl-color-text--primary-light"
    
    [[params.sections]]
    sectionId = "1"
    prettyName = "Home"
    path = ""
    
    [[params.sections]]
    sectionId = "2"
    prettyName = "Services"
    path = "services"
    
    [[params.sections]]
    sectionId = "3"
    prettyName = "Google for Work"
    subtitle = "Google for Work"
    path = "google-for-work"
    
    [[params.sections]]
    sectionId = "4"
    prettyName = "Google for Education"
    subtitle = "Google for Education"
    path = "google-for-education"
    
    # [[params.sections]]
    # sectionId = "3"
    # prettyName = "Partners & Clients"
    # background = "color-primary-dark"
    # partial = "home.html"
    
    # [[params.sections]]
    # sectionId = "4"
    # prettyName = "Contact us"
    # background = "color-primary-dark"
    # partial = "home.html"