baseurl = "loyall.ch"
languageCode = "en-us"
title = "Loyall"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
    description = ""
    author = "Pascal Aubort"
    googleAnalytics = ""
    #recaptchaSitekey = "6LeURygTAAAAAAfeKQjIzStD2zAPA3gRrxmA0oMK"
    
    languages = ["Français", "Deutsch", "English"]
    
    [params.layout]
    headerColor = "mdl-color--white"
    navigationLinkColor = "mdl-color-text--primary"
    navigationLinkColor_hover = "mdl-color-text--primary-light"
    
    [[params.sections]]
    sectionId = "1"
    prettyName = "Home"
    subtitle = "Trusted Advisor for your IT"
    # background = "color-primary-dark"
    partial = "home.html"
    
    [[params.sections]]
    sectionId = "2"
    prettyName = "About"
    subtitle = "Coming soon..."
    # background = "color-primary-dark"
    partial = "about.html"
    
    # [[params.sections]]
    # sectionId = "3"
    # prettyName = "Partners & Clients"
    # background = "color-primary-dark"
    # partial = "home.html"
    
    # [[params.sections]]
    # sectionId = "4"
    # prettyName = "Contact us"
    # background = "color-primary-dark"
    # partial = "home.html"